java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName: ccpay
  environment:
    POSTGRES_HOST: ccpay-bulkscanning-api-postgres-db-aat.postgres.database.azure.com
    POSTGRES_NAME: bspayment
    POSTGRES_USER: bspayment
    SPRING_LIQUIBASE_ENABLED: false
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - bulkscanning-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
