postgresql:
  initdbScripts:
    init.sql: |-
      CREATE USER ccpay-bulkscanning WITH PASSWORD 'ccpay-bulkscanning';
      CREATE DATABASE ccpay-bulkscanning WITH OWNER = ccpay-bulkscanning ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: ccpay-bulkscanning-db
  persistence:
    enabled: false

java:
  image: 'hmctspublic.azurecr.io/payment/ccpay-bulkscanning-api:latest'
  applicationPort: 8080
  environment:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-ccpay-bulkscanning-db:5432/ccpay-bulkscanning"
    SPRING_DATASOURCE_USERNAME: ccpay-bulkscanning
    SPRING_DATASOURCE_PASSWORD: ccpay-bulkscanning
    REFORM_SERVICE_NAME: ccpay-bulkscanning
    REFORM_TEAM: ccpay
    SPRING_LIQUIBASE_ENABLED: true

tags:
  postgresql-pod: true
