
java:
  image: 'hmctspublic.azurecr.io/payment/ccpay-bulkscanning-api:latest'
  applicationPort: 8080
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
    REFORM_SERVICE_NAME: ccpay-bulkscanning
    REFORM_TEAM: ccpay
    SPRING_LIQUIBASE_ENABLED: true
  postgresql:
    image:
      tag: 10.7.0-r68
    postgresqlUsername: bspayment
    postgresqlPassword: bspayment
    postgresqlDatabase: bspayment
    service:
      port: 5432
