java:
  image: 'hmctspublic.azurecr.io/ccpay/bulkscanning-api:latest'
  applicationPort: 8080
  ingressHost: ccpay-bulkscanning-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_HOST: ccpay-bulkscanning-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: bspayment
    POSTGRES_USERNAME: bspayment@ccpay-bulkscanning-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - bulkscanning-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
