java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName: ccpay
  environment:
    POSTGRES_HOST: ccpay-bulkscanning-api-postgres-db-aat.postgres.database.azure.com
    POSTGRES_NAME: bspayment
    POSTGRES_USERNAME: bspayment@ccpay-bulkscanning-api-postgres-db-aat
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.aat.platform.hmcts.net"
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - bulkscanning-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
