java:
  image: 'hmctspublic.azurecr.io/ccpay/bulkscanning-api:latest'
  applicationPort: 8080
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.aat.platform.hmcts.net"
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
    REFORM_SERVICE_NAME: ccpay-bulkscanning
    REFORM_TEAM: ccpay
    SPRING_LIQUIBASE_ENABLED: true
    APPINSIGHTS_INSTRUMENTATIONKEY: fake-key
  postgresql:
    image:
      tag: 10.7.0-r68
    postgresqlUsername: bspayment
    postgresqlPassword: bspayment
    postgresqlDatabase: bspayment
    service:
      port: 5432
